name: Rust Unit Tests

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Build
      run: cargo build --verbose
    - name: Run tests (nextest)
      run: cargo nextest run
